### ISSUE TITLE
testUnitPromotionWorkingInWorkTile unit test failure

### ISSUE THREAD

**Issue by HighwayofLife** [FreeCol/freecol#25]
```
    [junit] Testcase: testUnitPromotionWorkingInWorkTile(net.sf.freecol.server.model.ServerUnitTest):	FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit] 	at net.sf.freecol.server.model.ServerUnitTest.testUnitPromotionWorkingInWorkTile(ServerUnitTest.java:422)
    [junit] 	at junit.extensions.TestDecorator.basicRun(TestDecorator.java:23)
    [junit] 	at junit.extensions.TestSetup$1.protect(TestSetup.java:23)
    [junit] 	at junit.extensions.TestSetup.run(TestSetup.java:27)
    [junit] 
    [junit] 
    [junit] Test net.sf.freecol.AllTests FAILED
     [echo] For more detailed information about this test run see:
     [echo] /home/travis/build/FreeCol/freecol/build/report/TEST-net.sf.freecol.AllTests.txt
BUILD FAILED
/home/travis/build/FreeCol/freecol/build.xml:737: Automated Unit Tests failed.
```

**Comment by mpope042** [comment]
Fixed some time back.
