### ISSUE TITLE
Freecol doesn't load savegames, considered as map from map editor

### ISSUE THREAD

**Issue by Nserk** [FreeCol/freecol#34]
Whenever I try to load a savegame, Freecol reports that I'm trying to "start a map (from the map editor)", making it impossible to resume my game. I tried both playing an edited map and a random map, and the outcome is that the savegames aren't loaded.

net.sf.freecol.client.ClientOptions load
	INFO: Load OptionGroup(clientOptions) from F:\MyUser\Documenti\freecol\maps\3a09b009_olandese_1626_1_Spring.fsg succeeded
	Wed Jan 23 10:01:00 CET 2019
	Thread: 17
net.sf.freecol.FreeCol setName
	INFO: Set FreeCol.name = mapEditor
	Wed Jan 23 10:01:00 CET 2019
	Thread: 17
net.sf.freecol.server.FreeColServer readGame
	INFO: Found savegame version 14
	Wed Jan 23 10:01:00 CET 2019
	Thread: 17
net.sf.freecol.client.FreeColClient failToMain
	WARNING: Errore di inizializzazione del server
	Wed Jan 23 10:01:00 CET 2019
	Thread: 17
	Stack trace:
net.sf.freecol.common.FreeColException: error.mapEditorGame
	at net.sf.freecol.server.FreeColServer.readGame(FreeColServer.java:1009)
	at net.sf.freecol.server.FreeColServer.loadGame(FreeColServer.java:1076)
	at net.sf.freecol.server.FreeColServer.<init>(FreeColServer.java:321)
	at net.sf.freecol.client.FreeColClient.startServer(FreeColClient.java:886)
	at net.sf.freecol.client.control.ConnectController.startSavedGame(ConnectController.java:423)
	at net.sf.freecol.client.control.InGameController.loadGame(InGameController.java:3661)
	at net.sf.freecol.client.gui.action.OpenAction.actionPerformed(OpenAction.java:53)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by wintertime** [comment]
You did not write -- how exactly -- you created the savegame and which game version you used?
If in 0.11.6 you played, used the mapeditor on the save, then loaded the "map" saved from mapeditor as a "savegame" into the game -- this is still unsupported. You can read more on that there: https://sourceforge.net/p/freecol/bugs/2976/
Besides that, meanwhile maps should in master version get a different file extension than savegames, to prevent such mistakes.

**Comment by mpope042** [comment]
Standalone maps are now .fsm files and this code has changed a fair bit, so we are out of date here.
