### ISSUE TITLE
ERROR:  'Attribute "categories" was already specified for element "shortcut".'

### ISSUE THREAD

**Issue by paulvi** [FreeCol/freecol#82]
White installing on Linux Ubuntu Desktop 18.04 LTS the latest nightly build (available from releases download), and I remember the same was for the latest stable,  
the launcher shortcut does not appear in Application list.

```
java -jar freecol-git-20201224-installer.jar

ERROR:  'Attribute "categories" was already specified for element "shortcut".'
ERROR:  'com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "categories" was already specified for element "shortcut".'
could not read shortcut spec!
com.izforge.izpack.adaptator.XMLException: Errornull at line 26, column 7 : javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "categories" was already specified for element "shortcut".
	at com.izforge.izpack.adaptator.impl.XMLParser.parseLineNrFromInputSource(Unknown Source)
	at com.izforge.izpack.adaptator.impl.XMLParser.parse(Unknown Source)
	at com.izforge.izpack.adaptator.impl.XMLParser.parse(Unknown Source)
	at com.izforge.izpack.panels.ShortcutPanel.readShortcutSpec(Unknown Source)
	at com.izforge.izpack.panels.ShortcutPanel.panelActivate(Unknown Source)
	at com.izforge.izpack.installer.InstallerFrame.switchPanel(Unknown Source)
	at com.izforge.izpack.installer.InstallerFrame.navigateNext(Unknown Source)
	at com.izforge.izpack.installer.InstallerFrame.navigateNext(Unknown Source)
	at com.izforge.izpack.installer.InstallerFrame$NavigationHandler.navigate(Unknown Source)
	at com.izforge.izpack.installer.InstallerFrame$NavigationHandler.access$100(Unknown Source)
	at com.izforge.izpack.installer.InstallerFrame$NavigationHandler$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.xml.transform.TransformerException: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "categories" was already specified for element "shortcut".
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:786)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:370)
	... 12 more
Caused by: javax.xml.transform.TransformerException: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "categories" was already specified for element "shortcut".
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getDOM(TransformerImpl.java:597)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:776)
	... 13 more
Caused by: com.sun.org.apache.xml.internal.utils.WrappedRuntimeException: Attribute "categories" was already specified for element "shortcut".
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.dom.XSLTCDTMManager.getDTM(XSLTCDTMManager.java:426)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.dom.XSLTCDTMManager.getDTM(XSLTCDTMManager.java:214)
	at java.xml/com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.getDOM(TransformerImpl.java:575)
	... 14 more
```

**Comment by mpope042** [comment]
Not seeing any FreeCol code in those tracebacks.  Looks like an installer (izPack) issue.  Anyone understand what izPack is complaining about?  AFAICT we have been invoking it from the ant build.xml file since 2007 without problems, but apparently something has changed (on Ubuntu at least).  Stian wrote the ant stuff, and he is no longer active, so progress here will require someone who is running ubuntu and knows/can-learn izPack.

**Comment by paulvi** [comment]
Yes, that is definitely izPack issue
and it stopped working fully in latest OSes

**Comment by mpope042** [comment]
Found this again when trying to build a release.  There was an obvious duplication, and should now be fixed.
